import { NextRequest, NextResponse } from 'next/server';
import { forwardLeadToGhl } from '@/lib/ghl';
import { createSmtpTransporter, getAuditInboxEmail, getMailFrom } from '@/lib/smtp';

export const dynamic = 'force-dynamic';

export async function POST(request: NextRequest) {
  console.log('📧 API Route: send-audit-email called');

  try {
    const body = await request.json();
    console.log('📧 Request body:', body);

    const { name, email, phone, domain, timestamp } = body;

    if (!name || !email || !phone || !domain) {
      console.log('📧 Validation failed - missing fields');
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    const ts = timestamp || new Date().toISOString();

    void forwardLeadToGhl({
      source: 'audit_request',
      name,
      email,
      phone,
      domain,
      timestamp: ts,
    });

    const transporter = createSmtpTransporter();
    const from = getMailFrom();
    const to = getAuditInboxEmail();

    const mailOptions = {
      from,
      to,
      subject: `New SEO Audit Request - ${domain}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #fbbf24; background: #1f2937; padding: 20px; margin: 0; text-align: center; border-radius: 8px 8px 0 0;">
            🔍 New SEO Audit Request
          </h2>
          <div style="background: #f9fafb; padding: 30px; border-radius: 0 0 8px 8px;">
            <h3 style="color: #374151; margin-top: 0;">Contact Information</h3>
            <table style="width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
              <tr>
                <td style="padding: 12px 16px; border-bottom: 1px solid #e5e7eb; font-weight: bold; color: #374151; background: #f8fafc;">Name:</td>
                <td style="padding: 12px 16px; border-bottom: 1px solid #e5e7eb; color: #6b7280;">${name}</td>
              </tr>
              <tr>
                <td style="padding: 12px 16px; border-bottom: 1px solid #e5e7eb; font-weight: bold; color: #374151; background: #f8fafc;">Email:</td>
                <td style="padding: 12px 16px; border-bottom: 1px solid #e5e7eb; color: #6b7280;">${email}</td>
              </tr>
              <tr>
                <td style="padding: 12px 16px; border-bottom: 1px solid #e5e7eb; font-weight: bold; color: #374151; background: #f8fafc;">Phone:</td>
                <td style="padding: 12px 16px; border-bottom: 1px solid #e5e7eb; color: #6b7280;">${phone}</td>
              </tr>
              <tr>
                <td style="padding: 12px 16px; border-bottom: 1px solid #e5e7eb; font-weight: bold; color: #374151; background: #f8fafc;">Domain:</td>
                <td style="padding: 12px 16px; border-bottom: 1px solid #e5e7eb; color: #6b7280;">${domain}</td>
              </tr>
              <tr>
                <td style="padding: 12px 16px; font-weight: bold; color: #374151; background: #f8fafc;">Request Time:</td>
                <td style="padding: 12px 16px; color: #6b7280;">${new Date(ts).toLocaleString()}</td>
              </tr>
            </table>

            <div style="margin-top: 30px; padding: 20px; background: linear-gradient(135deg, #fef3c7, #fde68a); border-left: 4px solid #f59e0b; border-radius: 8px;">
              <p style="margin: 0; color: #92400e; font-weight: bold; font-size: 16px;">
                ⚡ Action Required: Please process this audit request and send the report to the client.
              </p>
            </div>

            <div style="margin-top: 20px; text-align: center;">
              <a href="mailto:${email}" style="display: inline-block; background: #fbbf24; color: #1f2937; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; margin-right: 10px;">
                Reply to Client
              </a>
              <a href="tel:${phone}" style="display: inline-block; background: #10b981; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold;">
                Call Client
              </a>
            </div>
          </div>
          <div style="background: #1f2937; padding: 20px; text-align: center; color: #9ca3af; border-radius: 0 0 8px 8px;">
            <p style="margin: 0;">Best regards,<br><strong>SEOInForce Assistant</strong></p>
            <p style="margin: 10px 0 0 0; font-size: 12px;">This email was automatically generated by the SEOInForce Assistant</p>
          </div>
        </div>
      `,
    };

    if (!transporter || !from || !to) {
      console.warn('📧 SMTP not configured; skipping send (set SMTP_USER/SMTP_PASS, SMTP_FROM, AUDIT_EMAIL or ADMIN_EMAIL)');
      console.log('📧 FALLBACK - AUDIT EMAIL DATA:', { name, email, phone, domain, ts });
      return NextResponse.json({
        success: true,
        message: 'Lead captured; email skipped (SMTP not configured)',
        messageId: `audit-${Date.now()}`,
      });
    }

    try {
      const result = await transporter.sendMail(mailOptions);
      console.log('📧 Email sent successfully:', result.messageId);
      return NextResponse.json({
        success: true,
        message: 'Audit request email sent successfully',
        messageId: result.messageId,
      });
    } catch (emailError) {
      console.error('📧 Email sending failed:', emailError);
      console.log('📧 FALLBACK - AUDIT EMAIL DATA:', { name, email, phone, domain, ts });
      return NextResponse.json({
        success: true,
        message: 'Audit request logged (email failed, check console)',
        messageId: `audit-${Date.now()}`,
      });
    }
  } catch (error) {
    console.error('📧 Error sending audit email:', error);
    return NextResponse.json(
      { error: 'Failed to send email', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    );
  }
}
